---
# tasks file for Prictice1

- name: Ensure Apache package is installed
  ansible.builtin.dnf:
    name: "{{ var_package }}"
    state: present
    
# name: Start and enable Apache service
 # ansible.builtin.service:
#    name: "{{ var_service }}"
#    state: started
#    enabled: true
    
- name: Allow Apache service on firewall
  ansible.posix.firewalld:
    service: "{{ var_firewall_service }}"
    immediate: true
    permanent: true
    state: enabled

- name: Add port to firewall
  ansible.posix.firewalld:
   port: "{{ var_firewall_port }}/tcp"
   permanent: true
   state: enabled
   #setype: "{{ var_seport_type }}"
  
- name: Change Apache port to 18111
  lineinfile:
   path: /etc/httpd/conf/httpd.conf
   regexp: '^Listen'
   line: 'Listen 18111'
  notify: restart httpd 
  
- name: Setting Selinux
  community.general.seport:
    ports: 18111
    proto: tcp
    setype: http_port_t
    state: present
